# Generated by Django 4.2.4 on 2023-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0004_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="url",
            field=models.URLField(default="default", max_length=2000),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
