# Generated by Django 4.2.4 on 2023-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0005_image_url_delete_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="Untitled", max_length=50),
        ),
    ]
