# Generated by Django 4.2.4 on 2023-09-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0009_alter_processparameters_blur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
