# Generated by Django 4.2.4 on 2023-09-15 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasksolver", "0010_alter_image_image_alter_image_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        default=100,
                        validators=[django.core.validators.MaxValueValidator(100000)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
        migrations.DeleteModel(
            name="ProcessParameters",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["-number"], name="tasksolver__number_9cdeff_idx"
            ),
        ),
    ]
