# Generated by Django 4.2.4 on 2023-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0011_task_remove_image_user_delete_processparameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_running",
            field=models.BooleanField(default=True),
        ),
    ]
