# Generated by Django 4.2.4 on 2023-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0012_task_is_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_running",
            field=models.BooleanField(default=False),
        ),
    ]
