# Generated by Django 4.2.4 on 2023-09-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0014_task_result_alter_task_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
