# Generated by Django 4.2.4 on 2023-10-11 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasksolver", "0016_alter_task_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_started",
        ),
        migrations.AlterField(
            model_name="task",
            name="number",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10000000),
                ],
            ),
        ),
    ]
