# Generated by Django 4.2.4 on 2023-10-12 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
    ]
