# Generated by Django 4.2.4 on 2023-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_profile_date_of_birth_remove_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
